"""Fixed a misspelling in a model

Revision ID: 6e63b3f73329
Revises: 259e8c43eedb
Create Date: 2021-06-08 08:33:33.795108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e63b3f73329'
down_revision = '259e8c43eedb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hikes', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('hikes', 'desription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hikes', sa.Column('desription', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('hikes', 'description')
    # ### end Alembic commands ###
