"""Working on users table

Revision ID: 5b4acd0703b0
Revises: ffdc0a98111c
Create Date: 2021-06-01 18:30:00.483383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4acd0703b0'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('profile_photo', sa.String(), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'profile_photo')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
