"""Remove email from user

Revision ID: 09c41cda3a4e
Revises: 79f6bdc46267
Create Date: 2021-06-02 17:19:23.440337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c41cda3a4e'
down_revision = '79f6bdc46267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
